version: "3.7"

services:

  # https://doc.traefik.io/traefik/getting-started/quick-start/

  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - "9091:9091/tcp"
      - "54914:54914/tcp"
      - "51820:51820/udp"
    volumes:
      - /share/CACHEDEV1_DATA/Container/wireguard/wgraoul.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=admin
      - PASS=Tr@nsm1ss10n!!
    volumes:
      - /share/CACHEDEV1_DATA/Container/transmission/config:/config
      - /share/CACHEDEV1_DATA/Download:/downloads
      - /share/CACHEDEV1_DATA/Download/watch:/watch
    restart: always

  # https://github.com/linuxserver/docker-radarr

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
    volumes:
      - /share/CACHEDEV1_DATA/Container/radarr/config:/config
      - /share/CACHEDEV1_DATA/Multimedia/Movies:/movies
      - /share/CACHEDEV1_DATA/Download:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.nas.docker`)
      - traefik.port=80

  # https://github.com/linuxserver/docker-sonarr

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
    volumes:
      - /share/CACHEDEV1_DATA/Container/sonarr/config:/config
      - /share/CACHEDEV1_DATA/Multimedia/TvShow:/tv
      - /share/CACHEDEV1_DATA/Download:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.nas.docker`)
      - traefik.port=80

  # https://hub.docker.com/r/randomninjaatk/lidarr-extended

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=501
      - PGID=501
      - TZ=Europe/Paris
    volumes:
      - /share/CACHEDEV1_DATA/Container/lidarr/config:/config
      - /share/CACHEDEV1_DATA/Download:/downloads
      - /share/CACHEDEV1_DATA/Multimedia/Music:/music
      - /share/CACHEDEV1_DATA/Container/lidarr/custom-services.d:/custom-services.d
      - /share/CACHEDEV1_DATA/Container/lidarr/custom-cont-init.d:/custom-cont-init.d
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.nas.docker`)
      - traefik.port=80

  # https://github.com/linuxserver/docker-prowlarr

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
    volumes:
      - /share/CACHEDEV1_DATA/Container/prowlarr/config:/config
      - /share/CACHEDEV1_DATA/Download/watch:/downloads # transmission watch directory
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.nas.docker`)
      - traefik.port=80

  # https://github.com/linuxserver/docker-bazarr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /share/CACHEDEV1_DATA/Container/bazarr/config:/config
      - /share/CACHEDEV1_DATA/Multimedia/Movies:/movies
      - /share/CACHEDEV1_DATA/Multimedia/TvShow:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.nas.docker`)
      - traefik.port=80

  # https://github.com/flaresolverr/flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVERnone
      - TZ=Europe/Paris
    ports:
      - "8191:8191"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.nas.docker`)
      - traefik.port=80

  # https://github.com/cstaelen/tidarr

  tidarr:
    image: cstaelen/tidarr:latest
    container_name: 'tidarr'
    volumes:
      - /share/CACHEDEV1_DATA/Container/tidarr/config:/home/app/standalone/shared
      - /share/CACHEDEV1_DATA/Multimedia/Music/_tidarr:/home/app/standalone/library
    restart: 'unless-stopped'
    ports:
      - 8484:8484
    environment:
      - TZ=Europe/Paris
      - ENABLE_BEETS=true
      - REACT_APP_TIDAL_COUNTRY_CODE=FR
      - ENABLE_PLEX_UPDATE=true
      - PLEX_URL=http://192.168.1.20:32400
      - PLEX_LIBRARY=3
      - PLEX_TOKEN=xxxxxx-xxxxxx
      - PLEX_PATH=/share/CACHEDEV1_DATA/Multimedia/Music/_tidarr
      - ENABLE_GOTIFY=true
      - GOTIFY_URL=http://push.pi.docker
      - GOTIFY_TOKEN=xxxxxx
      - ADMIN_PASSWORD=xxxxxx
      - ENABLE_TIDAL_PROXY=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.tidarr.rule=Host(`tidarr.nas.docker`)
      - traefik.port=80
  
  # https://hub.docker.com/r/linuxserver/plex

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /share/CACHEDEV1_DATA/Container/plex/config:/config
      - /share/CACHEDEV1_DATA/Multimedia/TvShow:/share/CACHEDEV1_DATA/Multimedia/TvShow
      - /share/CACHEDEV1_DATA/Multimedia/Movies:/share/CACHEDEV1_DATA/Multimedia/Movies
      - /share/CACHEDEV1_DATA/Multimedia/Music:/share/CACHEDEV1_DATA/Multimedia/Music
    restart: unless-stopped

  # https://github.com/rommapp/romm

  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
      - DB_USER=romm-user # Should match MARIADB_USER in mariadb
      - DB_PASSWD=romm-passwd # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY= xxxxx # Generate a key with `openssl rand -hex 32`
      - IGDB_CLIENT_ID= # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET= # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#igdb
      - MOBYGAMES_API_KEY= # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#mobygames
      - STEAMGRIDDB_API_KEY= # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#steamgriddb
      - SCREENSCRAPER_USER= # Use your ScreenScraper username and password
      - SCREENSCRAPER_PASSWORD= # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#screenscraper
      - RETROACHIEVEMENTS_API_KEY= # https://api-docs.retroachievements.org/#api-access
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /share/CACHEDEV1_DATA/Container/romm/library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /share/CACHEDEV1_DATA/Container/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /share/CACHEDEV1_DATA/Container/romm/config:/romm/config # Path where config.yml is stored
    depends_on:
      romm-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.romm.rule=Host(`romm.nas.docker`)
      - traefik.http.services.romm.loadbalancer.server.port=8080
      - traefik.port=80

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=romm-passwd
      - MARIADB_ROOT_PASSWORD=root-passwd
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  # https://github.com/nicolargo/glances

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    pid: host
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/share/CACHEDEV1_DATA/Container/glances/glances.conf:/glances/conf/glances.conf"
    environment:
      GLANCES_OPT: "-C /glances/conf/glances.conf -w --enable-plugin sensors"
      TZ: "Europe/Paris"
    ports:
      - "61208:61208"
    labels:
      - "traefik.port=61208"
      - "traefik.frontend.rule=Host:glances.nas.docker"

  # https://github.com/portainer/agent

  portainer_edge_agent:
    image: 'portainer/agent:latest'
    ports:
      - "9001:9001"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    restart: always
    container_name: portainer_edge_agent

  # https://github.com/containrrr/watchtower/

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/CACHEDEV1_DATA/Container/watchtower/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://push.pi.docker
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=xxxxxx
